name: 几枝
description: 红豆生南国，春来发几枝。
full_description: '几枝：一句诗词，一个中国色。<br>
<br>+ 首页一句诗词、沉浸波浪
<br>+ 诗词小部件，可添加至桌面
<br>+ 诗词详情，查看该诗词全文和解释
<br>+ 中国色，一览目前已收集的中国色'
android: https://play.google.com/store/apps/details?id=com.hugo.jizhi
iOS: https://apps.apple.com/us/app/%E5%87%A0%E6%9E%9D/id1552874203
web: https://www.coolapk.com/apk/248825
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: 
companies:
